Repository antvis/data-set, pull requests merged in 2020-09, with the labels that each got.

#96 fix(#95): tag-cloud throw error
  package.json
  src/transform/tag-cloud.ts
Labels: PR: unreviewed, bug

#97 chore(tag-cloud): optimize type of word-cloud
  src/transform/tag-cloud.ts
  test/unit/transform/tag-cloud-spec.ts
Labels: PR: reviewed-approved, chore

#98 fix: 处理width和height可能为0的情况
  src/util/tag-cloud.ts
  test/bugs/98-spec.ts
Labels: PR: reviewed-approved, bug
