Repository antvis/data-set, pull requests merged in 2020-04, with the labels that each got.

#72 feat: Add sankey sort
  package.json
  src/transform/diagram/sankey.ts
Labels: PR: reviewed-approved, enhancement

#73 chore: release v11.0.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#74 refactor: sankey interface sort optional
  src/transform/diagram/sankey.ts
Labels: PR: reviewed-changes-requested, refactor

#75 fix: build error
  package.json
  webpack.config.js
Labels: PR: reviewed-changes-requested, bug
